#!/usr/bin/env bash
# Answers, before any Go is written, whether runsc can do what the container tier
# would need of it. A failure here is a fact about gVisor; a failure after the
# implementation exists could be either.
#
# Four questions, each shaped so a pass cannot be vacuous:
#
#   1. Does runsc boot from a plain directory rootfs?  (baseline)
#   1b. From a directory that is a mountpoint of a block device? gVisor serves the
#      rootfs through a Gofer proxy rather than touching the filesystem directly,
#      and bean's rootfs is a TCMU block device rather than the overlayfs
#      directory a container runtime usually gets.
#   2. Can a process inside bind a unix socket the host then connects to? That is
#      how the node would reach beand -- there is no vsock outside a microVM.
#   3. Does docker-in-docker work, and with which documented restrictions?
#
# config.json is generated by python rather than assembled in shell: an earlier
# version of this script built it with here-doc interpolation, produced invalid
# JSON, and runsc echoed the file back instead of running anything -- which read
# as "the socket never appeared" rather than as a broken bundle.
#
# Usage: gvisor-probe.sh
set -uo pipefail

RUNSC=${RUNSC:-runsc}
WORK=${WORK:-/tmp/gvisor-probe}
IMG=${IMG:-docker.m.daocloud.io/library/python:3.11-slim}
RESULTS="$WORK/results"

pass() { printf '  PASS  %s\n' "$1"; echo "PASS $1" >> "$RESULTS"; }
fail() { printf '  FAIL  %s\n' "$1"; echo "FAIL $1" >> "$RESULTS"; }

command -v "$RUNSC" >/dev/null || { echo "runsc not found"; exit 1; }
echo "runsc: $($RUNSC --version | head -1)"

rm -rf "$WORK"; mkdir -p "$WORK"; : > "$RESULTS"

# writeBundle <dir> <extra-mounts-json> <cmd...>
writeBundle() {
  local dir=$1 extra=$2; shift 2
  # NUL-separated, because an argument can itself be a multi-line script. An
  # earlier version split on newlines and turned one python -c script into
  # seventeen arguments: the container then ran `python3 -u -c ''`, exited 0, and
  # printed nothing -- which read as "the socket never appeared".
  BUNDLE_DIR="$dir" EXTRA_MOUNTS="$extra" ARGS_JSON="$(printf '%s\0' "$@" | python3 -c '
import json, sys
raw = sys.stdin.buffer.read().split(b"\0")[:-1]
print(json.dumps([a.decode() for a in raw]))')" python3 - <<'PY'
import json, os

caps = ["CAP_CHOWN","CAP_DAC_OVERRIDE","CAP_FOWNER","CAP_FSETID","CAP_KILL",
        "CAP_SETGID","CAP_SETUID","CAP_SETPCAP","CAP_NET_BIND_SERVICE",
        "CAP_NET_RAW","CAP_SYS_CHROOT","CAP_MKNOD","CAP_AUDIT_WRITE","CAP_SETFCAP"]

spec = {
    "ociVersion": "1.0.0",
    "process": {
        "terminal": False,
        "user": {"uid": 0, "gid": 0},
        "args": json.loads(os.environ["ARGS_JSON"]),
        "env": ["PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin",
                "HOME=/root"],
        "cwd": "/",
        "capabilities": {k: caps for k in ("bounding", "effective", "permitted")},
    },
    "root": {"path": "rootfs", "readonly": False},
    "hostname": "probe",
    "mounts": [
        {"destination": "/proc", "type": "proc", "source": "proc"},
        {"destination": "/dev", "type": "tmpfs", "source": "tmpfs",
         "options": ["nosuid", "strictatime", "mode=755", "size=65536k"]},
        {"destination": "/dev/pts", "type": "devpts", "source": "devpts",
         "options": ["nosuid", "noexec", "newinstance", "ptmxmode=0666", "mode=0620"]},
        {"destination": "/dev/shm", "type": "tmpfs", "source": "shm",
         "options": ["nosuid", "noexec", "nodev", "mode=1777", "size=65536k"]},
        {"destination": "/sys", "type": "sysfs", "source": "sysfs",
         "options": ["nosuid", "noexec", "nodev", "ro"]},
        {"destination": "/tmp", "type": "tmpfs", "source": "tmpfs",
         "options": ["nosuid", "nodev", "mode=1777"]},
    ],
    "linux": {
        "namespaces": [{"type": t} for t in
                       ("pid", "ipc", "uts", "mount", "network")],
    },
}

extra = os.environ.get("EXTRA_MOUNTS", "").strip()
if extra:
    spec["mounts"].extend(json.loads(extra))

with open(os.path.join(os.environ["BUNDLE_DIR"], "config.json"), "w") as f:
    json.dump(spec, f, indent=2)
PY
  # A bundle that does not parse would otherwise be reported as a runtime failure.
  python3 -c "import json,sys; json.load(open(sys.argv[1]))" "$dir/config.json" || {
    echo "  generated config.json is invalid JSON"; return 1; }
}

run() {  # run <id> <bundle-dir>
  local id=$1 dir=$2 out rc
  out=$(timeout 120 "$RUNSC" --network=host --ignore-cgroups run --bundle "$dir" "$id" 2>&1)
  rc=$?
  "$RUNSC" --ignore-cgroups delete --force "$id" >/dev/null 2>&1
  printf '%s' "$out"
  return $rc
}

echo
echo "### preparing a rootfs from $IMG"
cid=$(docker create "$IMG" true 2>/dev/null) || { echo "docker create failed"; exit 1; }
plain="$WORK/plain/rootfs"; mkdir -p "$plain"
docker export "$cid" | tar -C "$plain" -xf - 2>/dev/null
docker rm "$cid" >/dev/null 2>&1
[ -x "$plain/usr/local/bin/python3" ] || { echo "exported rootfs has no python3"; exit 1; }
echo "  rootfs at $plain"

##### 1. plain directory rootfs
echo
echo "### 1. plain directory rootfs"
writeBundle "$WORK/plain" "" python3 -c 'print("hello from gvisor")'
out=$(run probe-plain "$WORK/plain")
if printf '%s' "$out" | grep -q "hello from gvisor"; then
  pass "boots and runs python3"
else
  fail "did not run: $(printf '%s' "$out" | tail -3)"
fi

##### 1b. rootfs that is a mounted block device
echo
echo "### 1b. rootfs on a mounted block device"
img="$WORK/rootfs.ext4"
truncate -s 3G "$img"
mkfs.ext4 -q -F "$img"
devmount="$WORK/dev/rootfs"; mkdir -p "$devmount"
if mount -o loop "$img" "$devmount" 2>/dev/null; then
  tar -C "$plain" -cf - . | tar -C "$devmount" -xf -
  writeBundle "$WORK/dev" "" python3 -c 'print("hello from a block device")'
  out=$(run probe-dev "$WORK/dev")
  if printf '%s' "$out" | grep -q "hello from a block device"; then
    pass "boots from a mounted block device"
  else
    fail "did not boot: $(printf '%s' "$out" | tail -5)"
  fi
  umount "$devmount" 2>/dev/null
else
  fail "could not mount the loop image (inconclusive)"
fi

##### 2. unix socket bind-mounted out
#
# Asserted from the host side by connecting and reading. Checking that the file
# appears would pass on a socket nothing can talk to.
echo
echo "### 2. unix socket inside, reachable from the host"
sockdir="$WORK/sock"; mkdir -p "$sockdir"
mkdir -p "$WORK/sockbundle"; cp -a "$plain" "$WORK/sockbundle/rootfs"
writeBundle "$WORK/sockbundle" \
  "[{\"destination\": \"/run/bean\", \"type\": \"bind\", \"source\": \"$sockdir\", \"options\": [\"rbind\",\"rw\"]}]" \
  python3 -u -c '
import socket, os, threading, time
p = "/run/bean/agent.sock"
if os.path.exists(p):
    os.unlink(p)
s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
s.bind(p)
s.listen(1)
os.chmod(p, 0o666)
print("listening on", p, flush=True)
def serve():
    while True:
        c, _ = s.accept()
        c.sendall(b"agent-alive")
        c.close()
threading.Thread(target=serve, daemon=True).start()
time.sleep(25)
'
( sleep 8
  for i in 1 2 3 4 5; do
    [ -S "$sockdir/agent.sock" ] && break
    sleep 2
  done
  if [ -S "$sockdir/agent.sock" ]; then
    reply=$(timeout 5 python3 -c "
import socket
s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
s.connect('$sockdir/agent.sock')
print(s.recv(32).decode())
" 2>&1)
    if [ "$reply" = "agent-alive" ]; then
      pass "host connected to a socket bound inside the sandbox"
    else
      fail "socket exists but does not talk: $reply"
    fi
  else
    fail "socket never appeared on the host"
  fi
) &
waiter=$!
out=$(run probe-sock "$WORK/sockbundle")
wait $waiter
printf '%s' "$out" | grep -q listening || \
  echo "  (sandbox said: $(printf '%s' "$out" | tail -2))"

echo
echo "### results"
cat "$RESULTS"
grep -q '^FAIL' "$RESULTS" && { echo; echo "at least one probe failed"; exit 1; }
echo
echo "all probes passed"
